login/urls.py
from django.conf.urls import url
from django.contrib import admin
from login.views import *

urlpatterns = [
	url(r'^$', user_login),
	url(r'^user_logout/$',user_logout)
]

urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('login.urls')),
	url(r'^',include('configure_rules.urls')),
    url(r'^',include('features_config.urls'))
]

configure_rules/forms.py
from django import forms
from django.forms.widgets import Select
from shared.constants import *

class ConstantForm(forms.Form):
        constant_name = forms.CharField(required=True)
        constant_value = forms.IntegerField(required=True)
        
class PercentForm(forms.Form):
        percent_name = forms.CharField(required=True)
        percent_value = forms.IntegerField(required=True)

login/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response,render,redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_protect,csrf_exempt
from xena import local_settings
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.


@csrf_protect
def user_login(request):
        context = RequestContext(request)
        if(request.method == "POST"):
                email = request.POST.get('email')
                password = request.POST.get('password')
                user = authenticate(username=email, password=password)
                if user is not None:
                        login(request, user)
                        return HttpResponseRedirect('/default_rule')
#                         return render(request,'default_rule.html')
                else:
                        messages.error(request,'Invalid Credentials')
                return render(request,'login.html')
        return render(request,'login.html')

def user_logout(request):
    logout(request)
    messages.success(request,"Successfully logged out")
    return redirect('/')

#persistent cookie
"""def set_cookie(response, key, value, days_expire=7):
    max_age = days_expire * 24 * 60 * 60

    expires = datetime.datetime.strftime(datetime.datetime.utcnow() + datetime.timedelta(seconds=max_age),
                                         "%a, %d-%b-%Y %H:%M:%S GMT")
    response.set_cookie(key, value, max_age=max_age, expires=expires,
                        domain=SESSION_COOKIE_DOMAIN,
                        secure=None)

	#delete cookie on expire and logout
def delete_cookie(response, key):
    response.delete_cookie(key)
"""

templates/_message.html
{% if messages %}
<div class="row">
    <div class="col-md-12">
        {% for message in messages %}
            {% if message.tags == "success" %}
                <div class="alert alert-success">
                    <button id= "id_alert_success" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <span id="id_alert_success_message">{{message}}</span>
                </div>
            {% elif message.tags == "error" %}
                <div class="alert alert-danger">
                    <button id= "id_alert_danger" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <span id="id_alert_danger_message">{{message}}</span>
                </div>
            {% elif message.tags == "info" %}
                <div class="alert alert-info">
                    <button id= "id_alert_info" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <span id="id_alert_info_message">{{message}}</span>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}

templates/admin_base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="manju">
    <meta name="description" content="XENA">
    <title>XENA</title>
    
    <!-- load js libraries -->
    <script src="{% static 'js/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="/static/js/angular/angular.min.js"></script> 

    <!-- load css libraries -->
    <link rel="stylesheet" href="{% static 'pagecss/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    
</head>
<body>
{% if user.is_authenticated %}
<div class="navbar navbar-default navbar-static-top navbar-main" role="navigation">
        <div class="navbar-header">
            <img src="{% static 'img/ss-logo.png' %}" alt="logo" class="logo-default">
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <!-- <a href='http://www.shieldsquare.co/blog/customer-faq/' target='_blank' ><i style="font-size:14px; color:#696969;" class="fa fa-info-circle"></i> FAQ</a> -->
                <a href="#" class="dropdown-toggle avatar pull-right" style="padding-top:15px;" data-toggle="dropdown">
                    <span class="hidden-small">{{ user.username }}<b class="caret"></b></span>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="/user_logout/">
                        <i class="fa fa-sign-out"></i>Logout
                        </a>
                    </li>
                </ul>
            </li>
        <ul>
</div>
<aside class = "sidebar" style="width:190px;">
<ul class="nav nav-stacked">
    <li><a href="/default_rule/"><i class="fa fa-bars" style="color:#337ab7;" aria-hidden="true"></i>Rules</a></li>
    <li><a href="/rule_constants/"><i class="fa fa-hashtag" aria-hidden="true"></i>Constants</a></li>
    <li><a href = "/rule_percentages/"><i class="fa fa-percent" aria-hidden="true"></i>Percentages</a></li>
    <li><a href="/list_features/"><i class="fa fa-cog" style="color:#337ab7;" aria-hidden="true"></i>Features</a></li>
    <li><a href="/audit_log/"><i class="fa fa-history" style="color:#337ab7;" aria-hidden="true"></i>Audit Logs</a></li>
    <li><a href="/analytics/"><i class="fa fa-bar-chart" aria-hidden="true" style="color:#337ab7;"></i>Analytics</a></li>
</ul>
</aside>
{% endif %}
{% block content %} {% endblock %}

</body>
</html>
<script>
var pathname = window.location.pathname;
console.log(pathname);
    $('.nav > li > a[href="'+pathname+'"]').parent().addClass('active');
</script>

templates/analytics.html
{% extends "admin_base.html" %}
{% block content %}
{% block header %}
    <link rel="stylesheet" href="/static/css/bootstrap/font-awesome.min.css">
{% endblock %}
<!--<iframe src="http://192.168.50.24:5601/app/kibana#/dashboard/baebf5e0-202e-11e7-abef-b9adf1ec6015?embed=true&_g=(filters:!(),refreshInterval:('$$hashKey':'object:2542',display:'5+seconds',pause:!f,section:1,value:5000),time:(from:now-15m,interval:auto,mode:quick,timezone:Asia%2FKolkata,to:now))&_a=(filters:!(),options:(darkTheme:!t),panels:!((col:1,id:'10079130-1957-11e7-9604-a3aeef10db44',panelIndex:4,row:3,size_x:6,size_y:2,type:visualization),(col:7,id:d7519550-1acf-11e7-a7d3-dd2921bccd45,panelIndex:6,row:1,size_x:6,size_y:2,type:visualization),(col:1,id:'7a18e900-1b61-11e7-ae5e-d9513f2e36ec',panelIndex:7,row:1,size_x:6,size_y:2,type:visualization),(col:7,id:da0fef90-1b5f-11e7-ae5e-d9513f2e36ec,panelIndex:8,row:3,size_x:6,size_y:2,type:visualization),(col:1,id:'9e4cead0-1b64-11e7-b7da-6b3f0379b7c5',panelIndex:9,row:5,size_x:6,size_y:2,type:visualization),(col:1,id:'793a95f0-1b6c-11e7-b7da-6b3f0379b7c5',panelIndex:10,row:7,size_x:8,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'_type:xena+or+type:xenalog')),title:XENA-RULE-ANALYTICS,uiState:(P-10:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-4:(vis:(legendOpen:!f)),P-6:(vis:(legendOpen:!f)),P-8:(vis:(legendOpen:!f)),P-9:(vis:(legendOpen:!f))))" height="700" width="1000"></iframe>-->
<iframe src="http://192.168.50.24:5601/app/kibana#/dashboard/baebf5e0-202e-11e7-abef-b9adf1ec6015?embed=true&_g=(filters:!(),refreshInterval:('$$hashKey':'object:2542',display:'5+seconds',pause:!f,section:1,value:5000),time:(from:now-15m,interval:auto,mode:quick,timezone:UTC,to:now))&_a=(filters:!(),options:(darkTheme:!t),panels:!((col:1,id:'10079130-1957-11e7-9604-a3aeef10db44',panelIndex:4,row:3,size_x:6,size_y:2,type:visualization),(col:7,id:d7519550-1acf-11e7-a7d3-dd2921bccd45,panelIndex:6,row:1,size_x:6,size_y:2,type:visualization),(col:1,id:'7a18e900-1b61-11e7-ae5e-d9513f2e36ec',panelIndex:7,row:1,size_x:6,size_y:2,type:visualization),(col:7,id:da0fef90-1b5f-11e7-ae5e-d9513f2e36ec,panelIndex:8,row:3,size_x:6,size_y:2,type:visualization),(col:1,id:'9e4cead0-1b64-11e7-b7da-6b3f0379b7c5',panelIndex:9,row:5,size_x:8,size_y:2,type:visualization),(col:1,id:'793a95f0-1b6c-11e7-b7da-6b3f0379b7c5',panelIndex:10,row:9,size_x:8,size_y:4,type:visualization),(col:1,id:'0f46a900-2359-11e7-bb3a-2b96d84799c3',panelIndex:11,row:7,size_x:4,size_y:2,type:visualization),(col:9,id:'7b9dcc50-2359-11e7-bb3a-2b96d84799c3',panelIndex:12,row:5,size_x:4,size_y:4,type:visualization),(col:5,id:bd4d49f0-2359-11e7-bb3a-2b96d84799c3,panelIndex:13,row:7,size_x:4,size_y:2,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'_type:xena+or+type:xenalog')),title:XENA-RULE-ANALYTICS,uiState:(P-10:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-11:(vis:(defaultColors:('0+-+60':'rgb(255,245,240)','120+-+180':'rgb(251,106,74)','180+-+240':'rgb(203,24,29)','60+-+120':'rgb(252,187,161)'),legendOpen:!f)),P-12:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-13:(vis:(defaultColors:('0+-+30':'rgb(255,245,240)','30+-+60':'rgb(252,187,161)','60+-+90':'rgb(251,106,74)','90+-+120':'rgb(203,24,29)'),legendOpen:!f)),P-4:(vis:(legendOpen:!f)),P-6:(vis:(legendOpen:!f)),P-8:(vis:(legendOpen:!f)),P-9:(vis:(legendOpen:!f))))" height="700" width="1000"></iframe>
{% endblock %}

templates/audit_log.html
{% extends "admin_base.html" %}
{% load widget_tweaks %}
{% block content %}
{% block header %}
    <script src="/static/js/jquery/jquery.stickytableheaders.min.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap/font-awesome.min.css">
    <script src="/static/js/angular/json-tree.js"></script>
    <script src="/static/pagejs/audit-log.js"></script>
    <link rel="stylesheet" href="/static/css/json-tree.css">
    <style>
        .results tr[visible='false'],
        .no-result{
            display:none;
        }
        .results tr[visible='true']{
            display:table-row;
        }
        .counter{
                padding:8px; 
                color:#ccc;
        }
      
    </style>
{% endblock %}
<div ng-app="auditApp" ng-controller="auditCtrl" class="content">
    <header><h3>Audit Log</h3></header><hr>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Audit Logs
                    <!--<span class="counter pull-right"></span>--><input type="text" class="search pull-right" style="color:black;margin:-1px;" placeholder="Search..">
                </div>
            
                <div class="panel-body">

                    <table id = "audit-table" class="table table-hover results" cellpadding="0" fixed-table-headers="scrollable-area">
                    <thead style="background-color:#ddd;">
                        <tr>
                            <th>Rule Name</th>
                            <th>User</th>
                            <th>Old Values</th>
                            <th>New Values</th>
                            <th>Timestamp</th>
                            <!--<th>Action</th>-->
                        </tr>
                        <tr class="warning no-result">
                            <td><i class="fa fa-warning"></i> No results</td>
                         </tr>
                    </thead>
                    <tbody>
                        {% for d in data %}
                        <tr>
                            <td>{{d.name}}</td>
                            <td>{{d.user}}</td>
                            <td><json-tree object="{{d.old_value}}" start-expanded="false" root-name="'old'"></json-tree></td>
                            <td><json-tree object="{{d.new_value}}" start-expanded="false" root-name="'new'"></json-tree></td>
                            <td>{{d.timestamp}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                        
                    <ul class="pagination" style="margin-top:0px;">
                    {% if data.has_previous %}
                    {% endif %}
                    {% for page in data.paginator.page_range %}
                    {% if forloop.first %}
                        {% if data.paginator.count > 5 %}
                            <li><a class="pagelink" href="?page=1">&laquo;</a></li>
                        {% endif %}
                    {% endif %}
                    {% if data %}
                    {% if page == data.number %}
                    <li class="active"><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% elif page > data.number|add:"-3" and page < data.number  %}
                    <li ><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% elif page < data.number|add:"3" and page > data.number  %}
                    <li ><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% endif %}
                    {% endif %}
                    {% if forloop.last %}
                    {% if data.paginator.count > 5 %}
                    <li><a class="pagelink" href="?page={{ page }}" >&raquo;</a></li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="manju">
    <meta name="description" content="XENA">
    <title>XENA</title>
    
    <!-- load js libraries -->
    <script src="{% static 'js/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="/static/js/angular/angular.min.js"></script> 

    <!-- load css libraries -->
	<link rel="stylesheet" href="{% static 'pagecss/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
	
</head>
<body>
	<nav class="navbar navbar-fixed-top" style = "background-color:#f1f1f1;">
		<div class="navbar-header">
                	<img src="{% static 'img/ss-logo.png' %}" alt="logo" class="logo-default">
       	</div>
	</nav>
	
        {% block content %} {% endblock %}
</body>
</html>


      

templates/confirm-delete.html
<!-- confirm-delete modal -->
<div id="confirm-delete" class="modal fade" data-backdrop="static"  role="dialog">
        <div class="modal-dialog modal-md" style="margin-top:150px";>

                <!-- Modal content-->
                <div class="modal-content">
                        <div class="modal-body cnf-delete">
                        	<h4>Are you sure you want to delete the rule?</h4>
			</div>
                        <div class="modal-footer">
                                <button type="button" class="btn btn-success" ng-click="confirm_delete()">Yes</button>
				<button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
					
			</div>
                </div>
        </div>
</div>

templates/constants.html
{% extends "admin_base.html" %}
{% load widget_tweaks %}
{% block content %}
{% block header %}
    <script src="/static/js/jquery/jquery.stickytableheaders.min.js"></script>
    <script src="/static/js/angular/angular-filter.min.js"></script>
    <script src="/static/pagejs/constants.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap/font-awesome.min.css">
    <style>
        .results tr[visible='false'],
        .no-result{
            display:none;
        }
        .results tr[visible='true']{
            display:table-row;
        }
        .counter{
                padding:8px; 
                color:#ccc;
        }
        #constant-exists{
            display:inline-block;
            text-align:center;
            visibility:hidden;
        }
        #constant-exists::before{
            content:'';
            display:inline-block;
            height:100%;
            vertical-align:middle;
            width:0px;
        }
    </style>
{% endblock %}
<div class="content">
    <header><h3>Constants Configuration</h3></header><hr>
    <div class="alert alert-danger alert-dismissable" id="constant-exists" style="display:none;">
        Constant name already exists
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" action="" method="POST">
                {% if error %}
                    <div class="alert alert-danger">
                        <button id= "id_alert_danger" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span id="id_alert_danger_message">{{ error }}</span>
                    </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_constant_name">Constant </label>
                    {% if form.constant_name.errors %}
                    <div class="form-group has-error">
                    </div>
                    {% else %}
                    <div class="form-group">
                        {{ form.constant_name|add_class:"form-control"|attr:"placeholder:Name"}}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="id_constant_value">Value</label>
                    {% if form.constant_value.errors %}
                    <div class="form-group has-error">
                    </div>
                    {% else %}
                    <div class="form-group">
                        {{ form.constant_value|add_class:"form-control"|attr:"min:0" }}
                    </div>
                    {% endif %}
                </div>
                <button id="save-constant"  class="btn btn-success" type="submit" style="margin-left:5px;">Save</button>
                <!--<i class="fa fa-spinner fa-spin fa-2x fa-fw" id="loader"></i><span class="sr-only">Loading...</span>-->
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Constants
                    <!--<span class="counter pull-right"></span>--><input type="text" class="search pull-right" style="color:black;margin:-1px;" placeholder="Search..">
                </div>
            
                <div class="panel-body" style="max-height:500px;">

                    <table id = "constant-table" class="table table-hover results" cellpadding="0" fixed-table-headers="scrollable-area">
                    <thead style="background-color:#ddd;">
                        <tr>
                            <th>Name</th>
                            <th>Value</th>
                        </tr>
                        <tr class="warning no-result">
                            <td><i class="fa fa-warning"></i> No results</td>
                         </tr>
                    </thead>
                    <tbody>
                        {% for constant in constants %}
                        <tr>
                            <td>{{constant.name}}</td>
                            <td>{{constant.value}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                        
                    <ul class="pagination">
                    {% if constants.has_previous %}
                    {% endif %}
                    {% for page in constants.paginator.page_range %}
                    {% if forloop.first %}
                        {% if constants.paginator.count > 10 %}
                            <li><a class="pagelink" href="?page=1">&laquo;</a></li>
                        {% endif %}
                    {% endif %}
                    {% if constants %}
                    {% if page == constants.number %}
                    <li class="active"><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% elif page > constants.number|add:"-3" and page < constants.number  %}
                    <li ><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% elif page < constants.number|add:"3" and page > constants.number  %}
                    <li ><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% endif %}
                    {% endif %}
                    {% if forloop.last %}
                    {% if constants.paginator.count > 10 %}
                    <li><a class="pagelink" href="?page={{ page }}" >&raquo;</a></li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
{% block header %}
    <link href="/static/pagecss/login.css" rel="stylesheet"/>  
	<script src="/static/js/jquery/jquery.validate.min.js"></script>
	<script src="/static/js/jquery/additional-methods.min.js"></script>
	<link href="/static/css/jquery/tooltipster.min.css" rel="stylesheet">
	<script src="/static/js/jquery/jquery.tooltipster.min.js"></script>
{% endblock %}

<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-4 col-md-offset-4">
	    <div class="panel panel-login">
	    <div class="panel-heading">
		<div class="row">
		    <div class="col-xs-12">
	                <!--<a href="#" class="active" id="login-form-link" >Welcome to ShieldSquare</a>-->
		    </div>
		</div>
		<hr>
	    </div>
        <div class="panel-body">   
		<div class="row">
		    <div class="col-lg-12">
			<form id="login-form" action="/" method="post" role="form" style="display: block;">{% csrf_token %}
				<div class="error_msg">{{error}}</div>
                {% if messages %}
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                {% endif %}
			    <div class="form-group">
				<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email" required>
			    </div>
			    <div class="form-group">
			        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password" required>
				</div>
			    <div class="form-group">
				<div class="row">
				    <div class="col-sm-6 col-sm-offset-3">
						<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
				    </div>
				</div>
			    </div>
			</form>
			
		</div>
   	    </div>
	</div>
    </div>
   </div>
</div>
{% endblock %}

templates/percents.html
{% extends "admin_base.html" %}
{% load widget_tweaks %}
{% block content %}
{% block header %}
    <script src="/static/js/jquery/jquery.stickytableheaders.min.js"></script>
    <script src="/static/js/angular/angular-filter.min.js"></script>
    <script src="/static/pagejs/percents.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap/font-awesome.min.css">
    <style>
        .results tr[visible='false'],
        .no-result{
            display:none;
        }
        .results tr[visible='true']{
            display:table-row;
        }
        .counter{
                padding:8px; 
                color:#ccc;
        }
        #percent-exists{
            display:inline-block;
            text-align:center;
            visibility:hidden;
        }
        #percent-exists::before{
            content:'';
            display:inline-block;
            height:100%;
            vertical-align:middle;
            width:0px;
        }
    </style>
{% endblock %}
<div class="content">
    <header><h3>Percents Configuration</h3></header><hr>
    <div class="alert alert-danger alert-dismissable" id="percent-exists" style="display:none;">
        Constant name already exists
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" action="" method="POST">
                {% if error %}
                    <div class="alert alert-danger">
                        <button id= "id_alert_danger" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span id="id_alert_danger_message">{{ error }}</span>
                    </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_constant_name">Name </label>
                    {% if form.percent_name.errors %}
                    <div class="form-group has-error">
                    </div>
                    {% else %}
                    <div class="form-group">
                        {{ form.percent_name|add_class:"form-control"|attr:"placeholder:Name"}}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="id_constant_value">Value</label>
                    {% if form.percent_value.errors %}
                    <div class="form-group has-error">
                    </div>
                    {% else %}
                    <div class="form-group">
                        {{ form.percent_value|add_class:"form-control"|attr:"min:0" }}
                    </div>
                    {% endif %}
                </div>
                <button id="save-constant"  class="btn btn-success" type="submit" style="margin-left:5px;">Save</button>
                <!--<i class="fa fa-spinner fa-spin fa-2x fa-fw" id="loader"></i><span class="sr-only">Loading...</span>-->
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Percentages
                    <!--<span class="counter pull-right"></span>--><input type="text" class="search pull-right" style="color:black;margin:-1px;" placeholder="Search..">
                </div>
            
                <div class="panel-body" style="max-height:500px;">

                    <table id = "constant-table" class="table table-hover results" cellpadding="0" fixed-table-headers="scrollable-area">
                    <thead style="background-color:#ddd;">
                        <tr>
                            <th>Name</th>
                            <th>Value</th>
                        </tr>
                        <tr class="warning no-result">
                            <td><i class="fa fa-warning"></i> No results</td>
                         </tr>
                    </thead>
                    <tbody>
                        {% for percent in percents %}
                        <tr>
                            <td>{{percent.name}}</td>
                            <td>{{percent.value}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                        
                    <ul class="pagination">
                    {% if percents.has_previous %}
                    {% endif %}
                    {% for page in percents.paginator.page_range %}
                    {% if forloop.first %}
                        {% if percents.paginator.count > 10 %}
                            <li><a class="pagelink" href="?page=1">&laquo;</a></li>
                        {% endif %}
                    {% endif %}
                    {% if percents %}
                    {% if page == percents.number %}
                    <li class="active"><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% elif page > percents.number|add:"-3" and page < percents.number  %}
                    <li ><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% elif page < percents.number|add:"3" and page > percents.number  %}
                    <li ><a class="pagelink" href="?page={{page}}">{{ page }}</a></li>
                    {% endif %}
                    {% endif %}
                    {% if forloop.last %}
                    {% if percents.paginator.count > 10 %}
                    <li><a class="pagelink" href="?page={{ page }}" >&raquo;</a></li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}